spring:
  application:
    name: springSecurity
  security:
    user:
      name: mignon
      password: 123
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li0EakPy4zPzHhQ2
            client-secret: c671f7c83765a677e90eed62f1e7d8991de1c2bc
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          github: # <-- 这个 'github' 是 providerId，通常与 registrationId 相同
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security-demo
    username: root
    password: kingdyx0

  data:
    redis:
      host: localhost
      port: 6379

app:
  jwtSecret: YourSecretKeyForJWTGenerationAndValidationWhichShouldBeLongAndComplex
  jwtExpirationMs: 86400000   # 24h

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/**/*.xml

server:
  address: 127.0.0.1
  port: 80
logging:
  config: classpath:logback.xml


